version: "3.8"

services:
  api:
   # build:
   #   context: ./subscription-api
    image: gerrome/django-vuejs_api:1
    volumes:
      - .:/app3
      - static_volume:/app3/staticfiles
      - media_volume:/app3/mediafiles   
    ports:
      - 8000:8000

  app:
    #build:
    #  context: ./subscription-app
    image: gerrome/django-vuejs_app:1      
    ports:
      - "3000:3000"
    volumes:
      - static_volume:/app3/staticfiles
      - media_volume:/app3/mediafiles    
    depends_on:
      - api

  nginx:
    image: gerrome/django-vuejs_nginx:1
 #   build:
 #     context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app      

volumes:
  static_volume:
  media_volume:



